import { beforeEach, describe, expect, it, vi } from "vitest";

import {
  createUploadKey,
  finalKeyFor,
  isUserUploadKey,
  keyFromPublicUrl,
  publicUrlForKey,
} from "@/lib/r2";

beforeEach(() => {
  vi.stubEnv("R2_PUBLIC_URL", "https://files.example.com/");
});

describe("createUploadKey", () => {
  it("puts a random name with the file's extension under pending/ and the user", () => {
    const key = createUploadKey("user1", "My Photo.PNG");

    expect(key).toMatch(/^pending\/user1\/[0-9a-f-]{36}\.png$/);
    expect(createUploadKey("user1", "My Photo.PNG")).not.toBe(key);
  });
});

describe("isUserUploadKey", () => {
  const key = "pending/user1/0f8fad5b-d9cb-469f-a165-70867728950e.pdf";

  it("accepts the user's own generated keys", () => {
    expect(isUserUploadKey("user1", key)).toBe(true);
    expect(isUserUploadKey("user1", createUploadKey("user1", "a.pdf"))).toBe(true);
  });

  it("works with any user id format", () => {
    const id = "User_1-AbC";
    expect(isUserUploadKey(id, createUploadKey(id, "a.pdf"))).toBe(true);
  });

  it("rejects another user's key", () => {
    expect(isUserUploadKey("user2", key)).toBe(false);
  });

  it("rejects keys that weren't generated by createUploadKey", () => {
    expect(isUserUploadKey("user1", "pending/user1/../user2/x.pdf")).toBe(false);
    expect(isUserUploadKey("user1", "pending/user1/report.pdf")).toBe(false);
    expect(
      isUserUploadKey("user1", "user1/0f8fad5b-d9cb-469f-a165-70867728950e.pdf"),
    ).toBe(false);
    expect(isUserUploadKey("user1", `${key}/extra`)).toBe(false);
    expect(isUserUploadKey("user1", "0f8fad5b-d9cb-469f-a165-70867728950e.pdf")).toBe(false);
  });
});

describe("finalKeyFor", () => {
  it("drops the pending/ prefix", () => {
    expect(finalKeyFor("pending/user1/a.png")).toBe("user1/a.png");
  });
});

describe("public URLs", () => {
  it("builds the URL from R2_PUBLIC_URL without a doubled slash", () => {
    expect(publicUrlForKey("user1/a.png")).toBe("https://files.example.com/user1/a.png");
  });

  it("turns a stored URL back into its key", () => {
    expect(keyFromPublicUrl("https://files.example.com/user1/a.png")).toBe("user1/a.png");
  });

  it("returns null for URLs outside the bucket", () => {
    expect(keyFromPublicUrl("https://other.example.com/user1/a.png")).toBeNull();
    expect(keyFromPublicUrl("https://files.example.com/")).toBeNull();
  });
});
